name: Deploy Docker Server

on:
   push:
      tags: ["*"]
concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile   # Specify path if not root
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/math-web:latest
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/math-web:latest
            docker stop math-web || true
            docker rm math-web || true
            docker run -d --name math-web --restart=always -p 3037:3000 ${{ secrets.DOCKERHUB_USERNAME }}/math-web:latest

